spring.ai.openai.chat.model=gpt-4o
spring.ai.openai.chat.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.temperature=0.9
spring.ai.openai.chat.max-tokens=150
spring.ai.openai.chat.max-completion-tokens=1000


